### ISSUE TITLE
Lua Inspect

### ISSUE THREAD

**Issue by chxp82q** [basaran/awesomewm-machina#1]
Maybe add that this module uses `Inspect` to the readme?

**Comment by basaran** [comment]
it's not supposed to be there :) I must have left it somewhere during debugging. I will take care of it shortly.

**Comment by basaran** [comment]
It should be commented out now, please do fresh pull. I made some changes and added some other bindings as well. Let me know how it goes.

**Comment by basaran** [comment]
has everything worked okay?
