### ISSUE TITLE
When tab wibox appears, the titlebar resizes it's height

### ISSUE THREAD

**Issue by ChrisOboe** [basaran/awesomewm-machina#2]
My titlebar (of each single client) has a height of e.g 10 pixels. 
As soon as machina starts drawing the tab-wibox, the height titlebar of the window where the wibox is gets severely reduced. 
Even afterwards when i close a client and the tab-wibox dissappears, the titlebar stays at it's low height.

i would assume, that the tab-wibox shouldn't affect the titlebar height at all.

**Comment by basaran** [comment]
you are right, it shouldn't. It's a side product of my own setup (you can see the videos). I'm planning on cleaning up many things. In the meantime, can you try to comment:

https://github.com/basaran/awesomewm-machina/blob/5dc771cdc42546689cce0e8df9e3e51ff12b75ac/methods.lua#L1146

That should take out the top titlebar override.

**Comment by ChrisOboe** [comment]
Thank you! 
this fixed it.
 
I'm not sure if i should close this issue, or if you want to leave it open until you did the cleanup.

**Comment by basaran** [comment]
Great, glad it worked out. You can close it, this is already in my orgmode :)
