### ISSUE TITLE
emit signal when tabbars are cleared

### ISSUE THREAD

**Issue by ChrisOboe** [basaran/awesomewm-machina#3]
I've got titlebars on every border. 

When the tabbar appears, my titlebar at the bottom get's replaced with the tabbar. 
When the tabbar disappears, my old titlebar doesn't get restored. instead i get a new titlebar with 3 pixel height instead. 

I think this happens in clear_tabbar from helpers.lua. 
It would be nice if machina saves your existing titlebar and restores it (or alternatively if you could pass the titlebar you want to machina instead of a hardcoded 3px one)

**Comment by basaran** [comment]
The bottom bars we use for creating the tabs are actually `titlebars` themselves. That's how everything works smoothly without creating actual awesomewm widgets and placing them on the screen which would complicate the regions you create with layout-machi.

I think the most efficient way to handle this would be to `emit` a signal when tabbars are cleared to let users attach their own logic via their `rc.lua`. I added it to my todo the for the rewrite of machina.

**Comment by basaran** [comment]
I didn't want to make a commit before I test this out throughly, you can do this:

replace the function in helper.lua with:

```lua
local function clear_tabbar(c, position)
   if not c then return end
   local position = position or "bottom"
   local titlebar = awful.titlebar(c, {size=3, position=position})
   titlebar:setup{
      layout=wibox.layout.flex.horizontal, nil
   }
   c:emit_signal("tabbar_cleared", c);
end --|clears bottom tabbar
```

then in your rc.lua, you can put your own titlebar logic:

```lua
client.connect_signal("tabbar_cleared", function(c)
    awful.titlebar(c, {size=20, position = "bottom"})
end)
```

This will probably fire a few times but it shouldn't really effect rendering or anything. Give it a go.

**Comment by ChrisOboe** [comment]
With this change it works great.
